server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          # === User Service ===
          - id: user-service
            uri: http://user-service:8081
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=1

          # === Report Service ===
          - id: report-service
            uri: http://report-service:8082
            predicates:
              - Path=/api/reports/**
            filters:
              - StripPrefix=1
